sonar.projectKey=licenta-horeca
sonar.projectName=licenta-horeca
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src,database
sonar.java.binaries=backend/target/classes

sonar.exclusions=**/node_modules/**,**/target/**,**/out/**,**/.idea/**,**/.git/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_da891ad21580822cedec6763368f7b1b25b82439